#!/bin/sh

# Installation script for seqdb_engine
# 1) cp uniprotmusfilter.config.default uniprotmusfilter.config
#
# 2) Install
#

Usage=Install

#
#  Function called when the install fails.
#
installFailed ()
{
    echo "Installation Failed: `date`"
    exit 1
}

#
#  Verify the arguments to the script, there shouldn't be any
#
if [ $# -ne 0 ]
then
    echo "Usage: ${Usage}"
    installFailed
fi

# 
# Make sure config file exists
# 
cd `dirname $0`

TOP=`pwd`
CONFIG=uniprotmusfilter.config

# make sure config file exists and source it
if [ -r ${CONFIG} ]
then
    . ${CONFIG}
else
    echo "Cannot source configuration file: ${CONFIG}"
    installFailed
fi

# compile java classes
cd src
echo "Compiling uniprotfilter source code in ${TOP}/bin"
javac -d ${TOP}/classes *.java 
echo "Install complete"

#
# Check to see if this is a development installation
#
DEV=""
if [ "${INSTALL_TYPE}" = "dev" ]
then
    DEV="-d"
fi

#
# run DLAInstall for spseqload
#
echo 'running DLAINSTALL'
${DLAINSTALL} ${DEV}

#
# create the input directory if it doesn't exist.
#
if [ ! -d ${INPUTDIR} ]
then
    mkdir -p ${INPUTDIR}
fi


